# What do we want?
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
#  storageClassName: mylocalstorage
  storageClassName: cloud-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 7Gi

---
# How do we want it implemented locally
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: local-storage
#spec:
#  storageClassName: mylocalstorage
#  capacity:
#    storage: 20Gi
#  accessModes:
#    - ReadWriteOnce
#  hostPath:
#    path: "/mnt/some new/directory/structure/"
#    type: DirectoryOrCreate

---
# How do we want it implemented on AWS
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cloud-ssd
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2